### PR TITLE
Use coverage report as a primary source of files to mutate

### LINKED ISSUE #705: Infection fails with "Allowed memory size ... exhausted" for a project with a really big coverage
| Question    | Answer
| ------------| ---------------
| Infection version | 0.13.2
| Test Framework version | PHPUnit
| PHP version | 7.2
| Github Repo | https://github.com/vimeo/psalm 

Extracted from https://twitter.com/sorsoup/status/1140021198765658118

> Infection seems to be crashing when I try to run it to check the test suite of Psalm - output at (link: https://circleci.com/gh/bdsl/psalm/232) circleci.com/gh/bdsl/psalm/…
> 
> Don't know if I'm doing anything wrong.

Command line:

```bash
php -d memory_limit=12G ~/sites/infection/bin/infection --coverage=build/phpunit --only-covered --threads=4
```

Output:

```bash
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 7.5.12

    1 [============================] < 1 sec

Generate mutants...

Processing source code files:   0/543

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /infection/src/TestFramework/PhpUnit/Coverage/CoverageXmlParser.php on line 170
```

So it fails with when the coverage data is being accumulated in the following lines of the code (depending on how much `memory_limit` is set

* on [`src/TestFramework/PhpUnit/Coverage/CoverageXmlParser.php:170`](https://github.com/infection/infection/blob/b9ebc49f2b5fd923b848a2ea035f90577d02bc5c/src/TestFramework/PhpUnit/Coverage/CoverageXmlParser.php#L170)
* on [`src/TestFramework/Coverage/CodeCoverageData.php:220`](https://github.com/infection/infection/blob/b9ebc49f2b5fd923b848a2ea035f90577d02bc5c/src/TestFramework/Coverage/CodeCoverageData.php#L220)

Unfortunately, code coverage takes 2+ hours for Psalm, so here is a compressed archive of needed coverage files: https://www.dropbox.com/s/66tvd0tctfbdki3/phpunit.bz?dl=0 for commit https://github.com/vimeo/psalm/commit/4c57c67e2f1b821e2ef8aa0b00448ff24ce92201

### PR DESCRIPTION
**Pull request by sanmai**
This PR is a continuation of #1082. Primary goal of this PR is memory optimization. Fixes #705.

With big projects with huge coverage reports Infection still has a lot of difficulty. Major part of this problem stems from the fact that Infection loads virtually all PHPUnit coverage reports at the start, and then goes one by one over source files looking up each file in the reports to understand if it need mutating, where, how, and so on. Not only it is expensive to load all reports at once, but also working with them isn't fast. Basically, it is one big hash table, where Infection tries to access rows from here and from there. 
- Yes, it may worth [adding a cache](https://github.com/infection/infection/pull/1125), because, say, methods of  `XMLLineCodeCoverage` are called sequentially over data for the same file, but this isn't what I want to propose. 
- Yes, with some careful `ArrayAccess` application you can make [the `$coverage` array clever to load data only as needed](https://github.com/sanmai/infection/commit/e83d1511f2b8cf2c233b3eb28dd4ce4182eb5cab#diff-668eec250a6cee30c97758097868c31cR105), and neither this is what I want to propose.

### What's the idea?

If you'd look at the PHPUnit coverage reports, and how we parse them, you would notice that the coverage reports have the same file names we need. Therefore, instead of iterating over files on disk, we can iterate over coverage reports, parsing them one by one, and discarding them once we finish mutating a file.

There are some problems:

- We not only consider these reports, we also consider JUnit reports, joining them together. This procedure had to be split into two. First we load coverage files, select files we want to be mutated (covered, uncovered, filtered), and only then we add JUnit timings, proceeding with mutation.
- For BC reasons we have to consider files outside of coverage reports, therefore we collect them too, adding missing files at the end, but only if needed. Suffice to say if we'd went half-way towards proposal #1064, this part could be removed from our pipeline, chances are together with the configuration step where user enters source paths.

Overall I had to reshuffle a lot of things, while trying to not to rename them too much. E.g. old tests for the new parser should probably work, and so on.

### Numbers
Enough words, let's the numbers speak:

- [BlackFire diff for a partial Psalm run](https://blackfire.io/profiles/compare/87b519d7-db00-44b0-b507-a68c052e3331/graph)
- [BlackFire diff for a Psalm run with `--filter=src/Psalm/DocComment.php`](https://blackfire.io/profiles/compare/33bb5fb7-93a3-4ba3-8f24-588e904b2703/graph)

```diff
-Time: 38m 17s. Memory: 2.56GB
+Time: 31m 2s. Memory: 553.82MB
```
Isn't that nice for a change?

If you want to try it, try this with something big, like Psalm. If you like me don't have all the time in the world, note the setup instructions below. PCOV is a must there, otherwise:

```
php vendor/bin/phpunit --coverage-xml=build/logs/coverage-xml --log-junit=build/logs/junit.xml --stop-on-failure
php path/to/bin/infection -j8 --skip-initial-tests --coverage=build/logs --no-progress --only-covered
```
Notice how fast it goes about business. Try with the master version, also with `--no-progress`. 

<details>
  <summary>How to set up Psalm</summary>

- With Psalm you need to either use a .phar, or update `vendor/ocramius/package-versions/src/PackageVersions/Versions.php` (inside Psalm checkout) to return something instead of `\OutOfBoundsException`.

- For simplicity sake best to remove some integration tests:

    ` rm -f tests/TypeReconciliation/ConditionalTest.php tests/DocumentationTest.php tests/UnusedVariableTest.php tests/FunctionCallTest.php tests/TypeReconciliation/RedundantConditionTest.php tests/ReturnTypeTest.php tests/ConstantTest.php tests/ClassStringTest.php tests/MethodCallTest.php tests/AssertAnnotationTest.php tests/TraitTest.php tests/ValueTest.php tests/AnnotationTest.php tests/CallableTest.php tests/Template/FunctionTemplateTest.php tests/FileManipulationReturnTypeManipulationTest.php tests/UnusedVariableTest.php tests/TypeReconciliation/RedundantConditionTest.php tests/Loop/ForeachTest.php tests/TypeReconciliation/TypeTest.php tests/PropertyTypeTest.php tests/TypeReconciliation/TypeAlgebraTest.php tests/IssetTest.php tests/Template/ClassTemplateTest.php tests/ArrayAssignmentTest.php tests/PropertyTypeTest.php tests/ArrayFunctionCallTest.php tests/Template/ClassTemplateExtendsTest.php tests/FunctionCallTest.php tests/UnusedVariableTest.php tests/DocumentationTest.php tests/TypeReconciliation/ConditionalTest.php tests/Config/ConfigTest.php`

- I used the following `infection.json`:
```json
{
    "timeout": 50,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "build\/infection.log"
    },
    "mutators": {
        "@removal": true,
        "@return_value": true,
        "@zero_iteration": true
    }
}
```

- In Linux try running Infection with `systemd-run --scope -p MemoryLimit=8000M php ...` to limit the fallout in case a mutation triggers a nasty bug in one of the mutation processes.

</details>

### What's next?

First of all, this is a practical proposal. I'd like to see that Infection still works, and my limited testing shows it pretty much does. Let me be corrected, though, if you find it doesn't.

Second, I'm looking to see a consensus about this proposal, and if there's a consensus that this is good and proper, I'll proceed with the remaining tasks. Getting tests up to speed, etc.

If it'd get rejected, well, then at least I didn't spend time fixing tests for a feature nobody needs, so please bear with me.

#### Task list

- [x] It works
- [x] Profile it
- [x] Write explanation
- [x] Fix PHPStan warnings for `src/`
- [x] Fix old tests, cleanup, rinse and repeat
    - [x] Tests from #1131 
    - [x] Tests from #1125 
- [x] Add new tests
    - [x] tests/phpunit/FileSystem/SourceFileFilterTest.php                              
    - [x] tests/phpunit/TestFramework/Coverage/CoveredFileDataFactoryTest.php            
    - [x] tests/phpunit/TestFramework/Coverage/CoveredFileDataTest.php                   
    - [x] tests/phpunit/TestFramework/Coverage/CoveredFileNameFilterTest.php             
    - [x] tests/phpunit/TestFramework/Coverage/JUnit/TestFileDataAdderTest.php           
    - [x] tests/phpunit/TestFramework/Coverage/XmlReport/FileCodeCoverageProviderTest.php
    - [x] tests/phpunit/TestFramework/PhpUnit/Coverage/XmlCoverageParserTest.php     
- [x] Fix coverage issues, cleanup, rinse and repeat
- [x] Remove `@see`
- [x] removeNamespace() should be moved in a XPathFactory
- [x] Doc PR: not needed
- [x] Remove CoveredFileNameFilter
- [ ] rename LineCodeCoverage to Tracer?
- [ ] CoveredFileData could be named Trace?

Post-merge clean up:
- [ ] FileCodeCoverageProvider no longer needed, but heavily used in tests
- [ ] FileCodeCoverage and SourceFileData might be possible to merge

#### Review tips

- Start with MutationGenerator
- Next you'll see SourceFileDataFactory
- It feeds from PhpUnitXmlCoveredFileDataProvider, which is a thin wrapper around IndexXmlCoverageParser
- SourceFileDataFactory also uses SourceFileFilter, and JUnitTestExecutionInfoAdder
- And a feed of files from configuration.

### CODE REVIEW

**Comment by sanmai** [comment]
ping @infection/core 

If you could try this build on anything, even on Infection's master, to see if there are obvious UX/DX issues, which shouldn't be, I’d really appreciate it. 

There's a lot more to do, I didn't even start to review what I've done, and if I could know about any new UX issues, e.g. when something is obviously broken or works unexpectedly, this will be a big help.

**Comment by theofidry** [comment]
@sanmai any way to get a blackfire diff?

**Comment by sanmai** [comment]
@theofidry Here's one: https://blackfire.io/profiles/compare/7b0142d7-b38d-4e98-b00f-444a9daa58fe/graph

**Comment by sanmai** [comment]
Here's another one for Psalm: https://blackfire.io/profiles/compare/fc62b217-2368-422d-b178-4527486ea23c/graph

No doubt there's a lot to improve here speed-wise, but look at the peak memory change.

File: src/Configuration/ConfigurationFactory.php [hunk 1]
```diff
@@ -122,14 +123,21 @@ public function create(
...
+        );
+
         return new Configuration(
             $schema->getTimeout() ?? self::DEFAULT_TIMEOUT,
             $schema->getSource()->getDirectories(),
             $this->sourceFileCollector->collectFiles(
                 $schema->getSource()->getDirectories(),
                 $schema->getSource()->getExcludes(),
-                $filter
+                $sourceFileFilter->getFilterArray(),
```
Comment (sanmai) [inline src/Configuration/ConfigurationFactory.php]:
```suggestion
                $sourceFileFilter->getFilterArray()
```

File: src/Container.php [hunk 2]
```diff
@@ -154,11 +157,33 @@ public static function create(): self
...
+            TestFileDataAdder::class => static function (self $container): TestFileDataAdder {
+                return new TestFileDataAdder(
+                    $container->getTestFrameworkAdapter(),
+                    $container->getMemoizedTestFileDataProvider()
+                );
+            },
             XMLLineCodeCoverageFactory::class => static function (self $container): XMLLineCodeCoverageFactory {
                 return new XMLLineCodeCoverageFactory(
                     $container->getConfiguration()->getCoveragePath(),
                     $container->getIndexXmlCoverageParser(),
```
Comment (sanmai) [inline src/Container.php]:
```suggestion
                    $container->getIndexXmlCoverageParser()
```

File: src/FileSystem/SourceFileFilter.php [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+        array $sourceDirectories,
+        array $excludeDirectories,
+        string $filter
+    ) {
+        $this->sourceDirectories = $sourceDirectories;
+        $this->excludeDirectories = $excludeDirectories;
+        $this->filters = take(explode(',', $filter))
+            ->map('trim')
+            ->filter()
+            ->toArray();
```
Comment (theofidry) [inline src/FileSystem/SourceFileFilter.php]:
```suggestion
        $this->filters = array_filter(array_map(
            'trim',
            explode(',', $filter)
        ));
```

No need for a fancy wrapper here although I agree it's more elegant, I prefer to reduce the usage of it (like I do with `nikic/iter` when I use it) as it's still an increase of learning curve and of coupling

File: src/FileSystem/SourceFileFilter.php [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+            $this->iterableToIterator($input),
+            $this->filters,
+            []
+        );
+    }
+
+    /**
+     * @param iterable<SplFileInfo&CoveredFileData> $input
+     *
+     * @return \Iterator<SplFileInfo&CoveredFileData>
```
Comment (theofidry) [inline src/FileSystem/SourceFileFilter.php]:
```suggestion
     * @return Iterator<SplFileInfo&CoveredFileData>
```
(it has already been imported)

File: src/Mutation/Mutation.php [hunk 5]
```diff
@@ -80,7 +80,7 @@ class Mutation
     /**
      * @param Node[] $originalFileAst
      * @param array<string|int|float> $attributes
-     * @param CoverageLineData[] $tests
+     * @param array<CoverageLineData> $tests
```
Comment (theofidry) [inline src/Mutation/Mutation.php]: why that change here?

File: src/Process/Runner/Parallel/ParallelProcessRunner.php [hunk 6]
```diff
@@ -52,14 +52,6 @@
  */
 class ParallelProcessRunner
```
Comment (theofidry) [inline src/Process/Runner/Parallel/ParallelProcessRunner.php]: Those changes seem unrelated no? Would it be possible it to extract it in a dedicated PR to evaluate its impact there?

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+     * @var SplFileInfo
+     */
+    private $sourceFile;
+
+    /**
+     * @var CoverageFileData|null
+     */
+    private $coverageFileData;
+
+    /** @var iterable<CoverageFileData> */
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileData.php]: can you keep them in the multi-line form? It especially don't make sense when you use the other form just above :)

I wish there was a fixer for that one as well

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 8]
```diff
@@ -0,0 +1,138 @@
...
+    public function getCoverageFileData(): CoverageFileData
+    {
+        if ($this->coverageFileData !== null) {
+            return $this->coverageFileData;
+        }
+
+        foreach ($this->lazyCoverageFileData as $coverageFileData) {
+            $this->coverageFileData = $coverageFileData;
+
+            break;
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileData.php]: this condition looks really weird: it's as if you're iterating only once

File: src/TestFramework/Coverage/CoveredFileDataFactory.php [hunk 9]
```diff
@@ -0,0 +1,128 @@
...
+namespace Infection\TestFramework\Coverage;
+
+use Infection\Mutation\MutationGenerator;
+use Infection\TestFramework\Coverage\JUnit\TestFileDataAdder;
+use Infection\TestFramework\Coverage\XmlReport\PhpUnitXmlCoverageFactory;
+use Symfony\Component\Finder\SplFileInfo;
+use Webmozart\Assert\Assert;
+
+/**
+ * Assembles a ready feed of CoveredFileData from different sources. Feeds data into MutationGenerator. Does not known about differences between adapters and what not.
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataFactory.php]: Can we get some line returns to say not exceed a 100 lines limit here?

File: src/TestFramework/Coverage/CoveredFileDataFactory.php [hunk 10]
```diff
@@ -0,0 +1,128 @@
...
+     */
+    public function createCoverage(): iterable
+    {
+        $coverageFeed = $this->primaryCoverageProvider->createCoverage();
+
+        $filteredCoverageFeed = $this->filter->filter($coverageFeed);
+
+        $readyCoverageFeed = $this->testFileDataAdder->addTestExecutionInfo($filteredCoverageFeed);
+
+        if (is_array($this->sourceFiles) && $this->sourceFiles === []) {
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataFactory.php]: missing import for `is_array()`

File: src/TestFramework/Coverage/CoveredFileDataFactory.php [hunk 11]
```diff
@@ -0,0 +1,128 @@
...
+        }
+
+        // Since these are sorted sets, there should be a way to optimize.
+
+        foreach ($this->sourceFiles as $splFileInfo) {
+            $sourceFilePath = $splFileInfo->getRealPath();
+
+            Assert::string($sourceFilePath);
+
+            if (array_key_exists($sourceFilePath, $seenFiles)) {
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataFactory.php]: missing import for `array_key_exists()`

File: src/TestFramework/Coverage/CoveredFileDataFactory.php [hunk 12]
```diff
@@ -0,0 +1,128 @@
...
+        $seenFiles = [];
+
+        /** @var CoveredFileData $data */
+        foreach ($coverage as $data) {
+            $seenFiles[$data->getSplFileInfo()->getRealPath()] = true;
+
+            yield $data;
+        }
+
+        // Since these are sorted sets, there should be a way to optimize.
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataFactory.php]: I'm a bit confused at the comment

File: src/TestFramework/Coverage/CoveredFileDataFactory.php [hunk 13]
```diff
@@ -0,0 +1,128 @@
...
+    }
+
+    /**
+     * @param iterable<CoveredFileData> $coverage
+     *
+     * @return iterable<CoveredFileData>
+     */
+    private function appendUncoveredFiles(iterable $coverage): iterable
+    {
+        $seenFiles = [];
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataFactory.php]: `$checkedFiles`?

File: src/TestFramework/Coverage/CoveredFileDataProvider.php [hunk 14]
```diff
@@ -0,0 +1,49 @@
...
+ * @internal
+ */
+interface CoveredFileDataProvider
+{
+    /**
+     * @throws CoverageDoesNotExistException
+     *
+     * @return iterable<CoveredFileData>
+     */
+    public function createCoverage(): iterable;
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileDataProvider.php]: `provideFiles()`?

File: src/TestFramework/Coverage/CoveredFileNameFilter.php [hunk 15]
```diff
@@ -0,0 +1,64 @@
...
+ * @see CoveredFileDataFactory
+ *
+ * @internal
+ */
+final class CoveredFileNameFilter
+{
+    private $filter;
+
+    public function __construct(
+        SourceFileFilter $filter
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileNameFilter.php]: no need for a multi-line constructor here

File: src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php [hunk 16]
```diff
@@ -33,11 +33,13 @@
 
 declare(strict_types=1);
 
-namespace Infection\TestFramework\Coverage\XmlReport;
+namespace Infection\TestFramework\Coverage\JUnit;
```
Comment (theofidry) [inline src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php]: AFAICS those changes of namespaces could be done in a separate PR for a bit of clarity

File: src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php [hunk 17]
```diff
@@ -33,11 +33,13 @@
...
 
 use function array_key_exists;
 
 /**
+ * Caches parsed rows from JUnit report.
```
Comment (theofidry) [inline src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php]: Is that comment necessary? That is what memoizing is about

File: src/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageFactory.php [hunk 18]
```diff
@@ -36,19 +36,22 @@
...
 /**
+ * Source of primary coverage data. Used by CoveredFileDataFactory.
+ *
+ * @see CoveredFileDataFactory
+ *
  * @internal
  * @final
  */
-class PhpUnitXmlCoverageFactory
+class PhpUnitXmlCoverageFactory implements CoveredFileDataProvider
```
Comment (theofidry) [inline src/TestFramework/Coverage/XmlReport/PhpUnitXmlCoverageFactory.php]: `PhpUnitXmlCoveredFileDataFactory`?

File: src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverage.php [hunk 19]
```diff
@@ -36,131 +36,99 @@
...
 use Infection\TestFramework\Coverage\LineCodeCoverage;
 use Infection\TestFramework\Coverage\NodeLineRangeData;
-use function range;
 
 /**
+ * Used by CoveredFileData to implement LineCodeCoverage methods.
+ *
  * @internal
+ *
+ * @see CoveredFileData
```
Comment (theofidry) [inline src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverage.php]: Do you think those `@see` annotations are really necessary? I find it a bit confusing, if I want to see the usage I can look up for the usage, at least it will be guaranteed to be up to date data whereas those `@see` are unlikely to be kept up to date

File: src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverageFactory.php [hunk 20]
```diff
@@ -36,47 +36,39 @@
...
+        IndexXmlCoverageParser $coverageXmlParser
     ) {
         $this->coverageDir = $coverageDir;
         $this->coverageXmlParser = $coverageXmlParser;
-        $this->testFileDataProvider = $testFileDataProvider;
     }
 
     public function create(
         string $testFrameworkKey,
         TestFrameworkAdapter $adapter
```
Comment (theofidry) [inline src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverageFactory.php]: The parameter `$adapter` is not used and could be removed.

File: src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php [hunk 21]
```diff
@@ -74,30 +65,33 @@ public function __construct(string $coverageDir)
...
+            ->map(static function (CoveredFileData $data) {
+                yield $data->getSplFileInfo()->getRealPath() => $data->getCoverageFileData();
+            });
 
-        return $data;
+        return iterator_to_array($coverage, true);
     }
 
-    private static function createXPath(string $coverageContent): SafeDOMXPath
+    public static function createXPath(string $coverageContent): SafeDOMXPath
```
Comment (theofidry) [inline src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php]: Maybe this piece and its `removeNamespace()` should be moved in a `XPathFactory` utility class? (in the same namespace)

File: src/TestFramework/PhpUnit/Coverage/XmlCoverageParser.php [hunk 22]
```diff
@@ -0,0 +1,243 @@
...
+            $this->coverageDir . '/' . $this->relativeCoverageFilePath
+        ));
+
+        $sourceFileInfo = self::retrieveSourceFileInfo($xPath, $this->relativeCoverageFilePath, $this->projectSource);
+
+        return new CoveredFileData($sourceFileInfo, $this->getCoverageFileData($xPath));
+    }
+
+    /** @return iterable<CoverageFileData> */
+    private function getCoverageFileData(SafeDOMXPath $xPath): iterable
```
Comment (theofidry) [inline src/TestFramework/PhpUnit/Coverage/XmlCoverageParser.php]: `retrieveCoverageFileData`?

File: src/Process/Runner/Parallel/ParallelProcessRunner.php (hunk 6 above)
Comment (sanmai) [reply src/Process/Runner/Parallel/ParallelProcessRunner.php]: Yes, let's try this.

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 7 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileData.php]: You know, typing fast trying to get things done. I wish there was a fixer. Anyway, thanks for the reminder, I'll get these in order in the end.

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 8 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileData.php]: Exactly. `lazyCoverageFileData` is an iterator with a single element.

File: src/TestFramework/Coverage/CoveredFileDataFactory.php (hunk 9 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileDataFactory.php]: No prob.

File: src/TestFramework/Coverage/CoveredFileDataFactory.php (hunk 12 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileDataFactory.php]: Say you have a sequence of files from disk:

    A B C D E F

And have a sequence of covered files:

    A B C _ E F

See, here D is missing e.g. because it is excluded from the whitelist. We can detect these gaps as we go. But we need to verify that these are actually are sorted sets. So it's out of scope.

File: src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php (hunk 17 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php]: See, I didn't know that when I wrote this comment. And it wasn't obvious it is related to JUnit report. Can we keep it?

Or, say, rename the class so it'd be more obvious what it does.

File: src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverage.php (hunk 19 above)
Comment (sanmai) [reply src/TestFramework/Coverage/XmlReport/XMLLineCodeCoverage.php]: Well, they really help be navigate the code, find what comes with what. I will certainly keep them for now, but later they are easy to remove once we're done here.

**Comment by sanmai** [comment]
@theofidry thanks for the review! I will address remaining comments in code a bit later.

**Comment by theofidry** [comment]
>See, I didn't know that when I wrote this comment. And it wasn't obvious it is related to JUnit report. Can we keep it?

 I guess then

File: src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php (hunk 16 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php]: Sure, #1131

File: src/Mutation/Mutation.php (hunk 5 above)
Comment (sanmai) [inline src/Mutation/Mutation.php]:
```suggestion
     * @param CoverageLineData[] $tests
```

File: src/Mutator/NodeMutationGenerator.php [hunk 23]
```diff
@@ -134,6 +134,8 @@ private function generateForMutator(Node $node, Mutator $mutator): iterable
 
         $mutationByMutatorIndex = 0;
 
+        Assert::fileExists($this->filePath);
+
```
Comment (sanmai) [inline src/Mutator/NodeMutationGenerator.php]:
```suggestion
```

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 24]
```diff
@@ -0,0 +1,138 @@
...
+     * @see TestFileDataAdder
+     */
+    public function retrieveCoverageFileData(): CoverageFileData
+    {
+        if ($this->coverageFileData !== null) {
+            return $this->coverageFileData;
+        }
+
+        foreach ($this->lazyCoverageFileData as $coverageFileData) {
+            $this->coverageFileData = $coverageFileData;
```
Comment (sanmai) [inline src/TestFramework/Coverage/CoveredFileData.php]:
```suggestion
            $this->coverageFileData = $coverageFileData; // is a \Generator with one yield, thus it'll only trigger here
```

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 25]
```diff
@@ -0,0 +1,138 @@
...
+     * @see TestFileDataAdder
+     */
+    public function retrieveCoverageFileData(): CoverageFileData
+    {
+        if ($this->coverageFileData !== null) {
+            return $this->coverageFileData;
+        }
+
+        foreach ($this->lazyCoverageFileData as $coverageFileData) {
+            $this->coverageFileData = $coverageFileData; // is a \Generator with one yield, thus it'll only trigger here
```
Comment (sanmai) [inline src/TestFramework/Coverage/CoveredFileData.php]:
```suggestion
            $this->coverageFileData = $coverageFileData; // is a Generator with one yield, thus it'll only trigger here (or an array with one element)
```

File: src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php [hunk 26]
```diff
@@ -38,6 +38,8 @@
...
+ *
```
Comment (sanmai) [inline src/TestFramework/Coverage/JUnit/MemoizedTestFileDataProvider.php]:
```suggestion
```

File: src/Mutation/MutationGenerator.php [hunk 27]
```diff
@@ -99,15 +93,18 @@ public function __construct(
...
 
-        foreach ($this->sourceFiles as $fileInfo) {
+        /** @var CoveredFileData $fileData */
+        foreach ($coveredFiles as $fileData) {
             yield from $this->fileMutationGenerator->generate(
-                $fileInfo,
+                $fileData,
                 $onlyCovered,
-                $this->coverageProvider->createFor($fileInfo),
+                new FileCodeCoverage($fileData->retrieveCoverageFileData()),
```
Comment (sanmai) [inline src/Mutation/MutationGenerator.php]: This isn't good.

**Comment by theofidry** [comment]
@sanmai just in case: I'll be waiting for you to ping me again before doing another review

**Comment by sanmai** [comment]
@theofidry sure, no prob. But if you can see if there's a method or a class that isn't aptly named, I'd appreciate if you could do that before a full review. Thanks.

File: src/FileSystem/SourceFileFilter.php [hunk 28]
```diff
@@ -0,0 +1,111 @@
...
+
+    /**
+     * @return iterable<SplFileInfo>
+     */
+    public function __construct(string $filter)
+    {
+        $this->filters = array_filter(array_map(
+            'trim',
+            explode(',', $filter)
+        ));
```
Comment (sanmai) [inline src/FileSystem/SourceFileFilter.php]: I understand one can argue that with a single combo of `array_filter(array_map())` it may not make sense to use any wrappers, even if the wrapper does the same `array_filter` and `array_map`. Conversely, I will tend to disagree if we're talking several `array_*` calls in one place. They're a DX disaster, and parsing them is not what one wants to spend their invaluable minutes on, at least as I see it.

To make a point against learning curve and vendor lock-in arguments, I invite you as a contributor. Let's see if I can change your mind, and if not from the start, at least we might learn if there's anything more to be done about that.

**Comment by sanmai** [comment]
@theofidry can you see if I missed anything from #1107? I know I am missing several tests, but in regard of `src/` I'm not entirely sure.

**Comment by theofidry** [comment]
Ok will try to have a look tonight or tomorrow

**Comment by sanmai** [comment]
@theofidry @maks-rafalko Build is green.

File: src/TestFramework/Coverage/CoveredFileDataFactory.php (hunk 13 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileDataFactory.php]: Well, we don't do any checking with them.

File: src/FileSystem/SourceFileFilter.php [hunk 29]
```diff
@@ -0,0 +1,106 @@
...
+     * @return Iterator<SplFileInfo&CoveredFileData>
+     */
+    private function iterableToIterator(iterable $input)
+    {
+        if ($input instanceof Iterator) {
+            // Generator is an iterator, means most of the time we're done right here.
+            return $input;
+        }
+
+        // Clause for all other cases, e.g. when testing
```
Comment (maks-rafalko) [inline src/FileSystem/SourceFileFilter.php]: just to understand this bit of the code, could you please explain what it will be used for? Any example?

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 30]
```diff
@@ -0,0 +1,138 @@
...
+     */
+    private $coverageFileData;
+
+    /**
+     * @var iterable<CoverageFileData>
+     */
+    private $lazyCoverageFileData;
+
+    /**
+     * @var ?FileCodeCoverage
```
Comment (maks-rafalko) [inline src/TestFramework/Coverage/CoveredFileData.php]: makes sense to use only one way of documenting nullable types: `?Type` or `Type|null`.

For example, line 56 uses `Type|null`

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php [hunk 31]
```diff
@@ -33,71 +33,63 @@
...
     }
 
     /**
-     * @param CoverageFileData[] $coverage
+     * @param iterable<CoveredFileData> $coverage
+     *
+     * @return iterable<CoveredFileData>
      */
-    private function addTestExecutionInfo(array $coverage): void
+    private function testExecutionInfoAdder(iterable $coverage): iterable
```
Comment (maks-rafalko) [inline src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: not sure about the name of the method. IMO, previous version `addTestExecutionInfo()` is more self explained.

The new name does not mean we return or add anything.

Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: I'll bring it back.

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 30 above)
Comment (sanmai) [inline src/TestFramework/Coverage/CoveredFileData.php]:
```suggestion
     * @var FileCodeCoverage|null
```
Fair.

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php (hunk 31 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: `addTestExecutionInfo` is still there, a public method line 69 above. So we can have this renamed, but not into `addTestExecutionInfo`

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 30 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileData.php]: Fixed this and in another place.

File: src/Mutation/MutationGenerator.php [hunk 32]
```diff
@@ -99,15 +96,18 @@ public function __construct(
      */
     public function generate(bool $onlyCovered, array $nodeIgnorers): iterable
     {
-        $numberOfFiles = IterableCounter::bufferAndCountIfNeeded($this->sourceFiles, $this->runConcurrently);
+        $coveredFiles = $this->coveredFileDataProvider->provideFiles();
```
Comment (maks-rafalko) [inline src/Mutation/MutationGenerator.php]: It's a little bit confusing that variable and class named `covered...`, but actually we can provide uncovered files here as well:

```php
# CoveredFileDataFactory

// ...

if ($this->onlyCovered === true) {
    // The case where only covered files are considered
    return $readyCoverageFeed;
}

return $this->appendUncoveredFiles($readyCoverageFeed);
              ^^^
```

I would suggest to rename it to something that covers both covered an uncovered cases.

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 33]
```diff
@@ -0,0 +1,138 @@
...
+use Symfony\Component\Finder\SplFileInfo;
+use Webmozart\Assert\Assert;
+
+/**
+ * Workhorse AKA envelope for all things coverage-related in regard of mutators.
+ *
+ * @internal
+ * @final
+ */
+class CoveredFileData implements LineCodeCoverage
```
Comment (maks-rafalko) [inline src/TestFramework/Coverage/CoveredFileData.php]: New file `CoveredFileData` has a very similar name to already existing `CoverageFileData`, I even mixed them up during code review several times. Could we think about renaming it/them if possible?

File: src/TestFramework/Coverage/CoveredFileNameFilter.php [hunk 34]
```diff
@@ -0,0 +1,62 @@
...
+
+namespace Infection\TestFramework\Coverage;
+
+use Infection\FileSystem\SourceFileFilter;
+
+/**
+ * @internal
+ * @final
+ */
+class CoveredFileNameFilter
```
Comment (maks-rafalko) [inline src/TestFramework/Coverage/CoveredFileNameFilter.php]: Do we need this file? Or is it for better/easier testing?

Looks redundant for me

File: src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php [hunk 35]
```diff
@@ -74,50 +59,35 @@ public function __construct(string $coverageDir)
...
-     * Remove namespace to work with xPath without a headache
-     */
-    private static function removeNamespace(string $xml): string
-    {
-        /** @var string $cleanedXml */
-        $cleanedXml = preg_replace('/xmlns=\".*?\"/', '', $xml);
+            $fileInfoProvider = new SourceFileInfoProvider($this->coverageDir, $relativeCoverageFilePath, $projectSource);
 
-        Assert::string($cleanedXml);
+            $parser = new XmlCoverageParser($fileInfoProvider);
```
Comment (maks-rafalko) [inline src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php]: What do you think about creating this class 1 time before the loop and pass `$fileInfoProvider` to the `parse()` method?

**Comment by maks-rafalko** [comment]
Also, question. Can we somehow make sure that all those generators are work as developed and not "unbuffered" by mistake in the future? Some kind of automatic test. This is out of the scope of this PR but something would be nice to have.

What I would like to avoid, is a case when all this hard work and benefits of using generators will somehow be "break" by mistake / not careful usage of them.

**Comment by maks-rafalko** [comment]
`bin/infection --only-covered --no-progress -j4`

0.15.3:

```
1984 mutations were generated:
Covered Code MSI: 87%
Time: 4m 29s. Memory: 92.01MB
```

master:

```
2030 mutations were generated:
Covered Code MSI: 86%
Time: 2m 58s. Memory: 40.00MB
```

I have to say - these are really interesting results.

File: src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php (hunk 35 above)
Comment (sanmai) [reply src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php]: It is really hard to see it from the diff here, but $fileInfoProvider is also [called once per node](https://github.com/infection/infection/blob/bf44abc1ed5c94998ef7d7490c443d30f6069496/src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php#L82-L89).

File: tests/phpunit/FileSystem/SourceFileFilterTest.php [hunk 36]
```diff
@@ -0,0 +1,140 @@
...
+        $actual = take($actual)
+            ->map(static function (SplFileInfo $fileInfo) {
+                return $fileInfo->getRealPath();
+            })
+            ->toArray();
+
+        $this->assertSame($expected, $actual);
+    }
+
+    private function arrayToSplFileInfoTraversable(array $input): Traversable
```
Comment (theofidry) [inline tests/phpunit/FileSystem/SourceFileFilterTest.php]: Maybe I misunderstood but isn't the downstream API requiring an `iterable` here in which case we could just do a simple `array_map` and return an `array` instead?

File: src/Mutation/MutationGenerator.php (hunk 32 above)
Comment (sanmai) [reply src/Mutation/MutationGenerator.php]: Yes, true, I probably left these named this way after `CoveredFileData` objects, which, as I see it, should have a cousin `UnoveredFileData` following the same interface, but with slightly simplified internals. 

How does that feel if we'd name them `SourceFileDataSomething`?

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 33 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileData.php]: How about `CoverageReportData` instead of `CoverageFileData`?

File: src/TestFramework/Coverage/CoveredFileNameFilter.php (hunk 34 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileNameFilter.php]: Let me see about removing it.

File: src/Mutation/FileMutationGenerator.php [hunk 37]
```diff
@@ -85,21 +85,18 @@ public function generate(
...
-        $initialStatements = $this->parser->parse($fileInfo);
+        $sourceFilePath = $fileData->getSplFileInfo()->getPathname();
+
+        $initialStatements = $this->parser->parse($fileData->getSplFileInfo());
 
         $mutationsCollectorVisitor = new MutationsCollectorVisitor(
             new NodeMutationGenerator(
                 $mutators,
-                $filePath,
+                $sourceFilePath,
```
Comment (theofidry) [inline src/Mutation/FileMutationGenerator.php]: Minor change to avoid using `getSplFileInfo()` two times

```suggestion
        $fileInfo = $fileData->getSplFileInfo();

        $initialStatements = $this->parser->parse($fileInfo);

        $mutationsCollectorVisitor = new MutationsCollectorVisitor(
            new NodeMutationGenerator(
                $mutators,
                $fileInfo->getPathname(),
                $initialStatements,
                $codeCoverage,
                $onlyCovered,
                $this->lineRangeCalculator
            )
        );
```

File: src/Mutation/MutationGenerator.php (hunk 32 above)
Comment (theofidry) [reply src/Mutation/MutationGenerator.php]: In this case here we can name `$coveredFiles` to `$files` though

**Comment by sanmai** [comment]
> Can we somehow make sure that all those generators are work as developed and not "unbuffered" by mistake in the future?

This is a valid concern. Even if I made best effort to protect such cases by testing with a "never" iterator, I didn't do without instrumentation to guide my efforts. E.g. I had to know that I'm moving in the right direction. 

This metric I was optimising for was time-to-first-mutation. It was hacked together, to be honest, and not worthy present here, so it isn't, but it is not to say it can't be added in a clean way. I will make an issue of it, it this metric appears to make sense.

Another issue we might have is that these "never" iterators are not exactly obvious. You have to know what you're looking at.

```php
$mutations = $this->createMock(Iterator::class);
$mutations
    ->expects($this->never())
    ->method($this->anything())
 ;
```
It may be worth making these cases to use a consistent and visible approach, say, using a concrete `NeverIterator` class fixture.

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 33 above)
Comment (theofidry) [reply src/TestFramework/Coverage/CoveredFileData.php]: Maybe we can do that change in another PR but I would like to rename `LineCodeCoverage` to `Tracer` which is a more ubiquitous term for this concept of _tracing_ the source code to the tests or vice-versa. Hence `CoveredFileData` could be named `Trace here`

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 38]
```diff
@@ -0,0 +1,138 @@
...
+        // There's no point to have it parsed right away as we may not need it, e.g. because of a filter
+        $this->lazyCoverageFileData = $lazyCoverageFileData;
+    }
+
+    public function getSplFileInfo(): SplFileInfo
+    {
+        return $this->sourceFile;
+    }
+
+    public function getRealPath(): string
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileData.php]: is it worth having considering we are using it only in tests?

File: src/TestFramework/Coverage/CoveredFileData.php [hunk 39]
```diff
@@ -0,0 +1,138 @@
...
+
+        Assert::string($realPath);
+
+        return $realPath;
+    }
+
+    /**
+     * Accessor used to update CoverageFileData with TestFileTimeData.
+     */
+    public function retrieveCoverageFileData(): CoverageFileData
```
Comment (theofidry) [inline src/TestFramework/Coverage/CoveredFileData.php]: I'm not quite sure about that `FileCodeCoverage <-> CoveredFileData` relationship/API, will get back to it later

File: src/TestFramework/Coverage/CoveredFileDataFactory.php (hunk 13 above)
Comment (theofidry) [reply src/TestFramework/Coverage/CoveredFileDataFactory.php]: `$filesSeen`?

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php [hunk 40]
```diff
@@ -33,71 +33,63 @@
 
 declare(strict_types=1);
 
-namespace Infection\TestFramework\Coverage\XmlReport;
+namespace Infection\TestFramework\Coverage\JUnit;
```
Comment (theofidry) [inline src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: I thought that move was done in another PR?

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php (hunk 31 above)
Comment (theofidry) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: I guess it can be inlined here though since the name is not that compelling?

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php [hunk 41]
```diff
@@ -33,71 +33,63 @@
...
+use Infection\TestFramework\Coverage\CoveredFileData;
 
 /**
+ * Adds test execution info to selected covered file data object.
+ *
  * @internal
  * @final
  */
-class PhpUnitXmlCoverageFactory
+class TestFileDataAdder
```
Comment (theofidry) [inline src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: `JunitTestExecutionInfoAdder`
?

File: src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php [hunk 42]
```diff
@@ -35,43 +35,16 @@
...
-
-    private $coverageFactory;
-
-    public function __construct(PhpUnitXmlCoverageFactory $coverageFactory)
-    {
-        $this->coverageFactory = $coverageFactory;
-    }
-
-    public function provideFor(SplFileInfo $fileInfo): FileCodeCoverage
+    public function provideFor(CoveredFileData $fileData): FileCodeCoverage
```
Comment (theofidry) [inline src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php]: Is that provider still really needed?

File: src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php [hunk 43]
```diff
@@ -35,43 +35,16 @@
...
-            ? $fileInfo->getPathname()
-            : $fileInfo->getRealPath()
-        ;
-
-        if (!array_key_exists($filePath, $this->coverage)) {
-            return new FileCodeCoverage(new CoverageFileData());
-        }
-
-        return new FileCodeCoverage($this->coverage[$filePath]);
+        return new FileCodeCoverage($fileData->retrieveCoverageFileData());
```
Comment (theofidry) [inline src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php]: I'm not quite sure to understand why we need both `FileCodeCoverage` and `CoveredFileData`

File: src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php [hunk 44]
```diff
@@ -74,50 +59,35 @@ public function __construct(string $coverageDir)
...
+            $relativeCoverageFilePath = $node->getAttribute('href');
 
-    /**
-     * Remove namespace to work with xPath without a headache
-     */
-    private static function removeNamespace(string $xml): string
-    {
-        /** @var string $cleanedXml */
-        $cleanedXml = preg_replace('/xmlns=\".*?\"/', '', $xml);
+            $fileInfoProvider = new SourceFileInfoProvider($this->coverageDir, $relativeCoverageFilePath, $projectSource);
```
Comment (theofidry) [inline src/TestFramework/PhpUnit/Coverage/IndexXmlCoverageParser.php]:
```suggestion
            $fileInfoProvider = new SourceFileInfoProvider(
                $this->coverageDir, 
                $relativeCoverageFilePath, 
                $projectSource
            );
```

File: src/TestFramework/PhpUnit/Coverage/XPathFactory.php [hunk 45]
```diff
@@ -0,0 +1,74 @@
...
+
+use DOMDocument;
+use Infection\TestFramework\SafeDOMXPath;
+use function Safe\preg_replace;
+use Webmozart\Assert\Assert;
+
+/**
+ * @internal
+ */
+final class XPathFactory
```
Comment (theofidry) [inline src/TestFramework/PhpUnit/Coverage/XPathFactory.php]: can that be introduced in a separate PR?

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php (hunk 40 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: It did. It is Git thinks this file has something to do with PhpUnitXmlCoverageFactory

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php (hunk 31 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: `addTestExecutionInfo` isn't a generator, where this method is. So, no, can't be inlined, at least without a closure.

Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: OK, I made it an explicit generator. It as actually adding generator. Makes sense?

File: src/FileSystem/SourceFileFilter.php [hunk 46]
```diff
@@ -0,0 +1,115 @@
...
+        $this->filters = array_filter(array_map(
+            'trim',
+            explode(',', $filter)
+        ));
+    }
+
+    /**
+     * @return string[]
+     */
+    public function getFilters(): array
```
[the remark this answers is not in the document]
Comment (sanmai) [reply src/FileSystem/SourceFileFilter.php]: Well, I missed this. I guess it really makes so.

File: src/TestFramework/Coverage/CoveredFileDataFactory.php (hunk 13 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileDataFactory.php]: Done

File: src/TestFramework/Coverage/JUnit/TestFileDataAdder.php (hunk 41 above)
Comment (sanmai) [reply src/TestFramework/Coverage/JUnit/TestFileDataAdder.php]: Done

File: src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php (hunk 42 above)
Comment (sanmai) [reply src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php]: Yes and no. The whole purpose of this file is to save my time on conflict resolution. I guess I can add it to some post-merge clean up list, how do you think?

File: tests/phpunit/FileSystem/SourceFileFilterTest.php [hunk 47]
```diff
@@ -0,0 +1,140 @@
...
+            'src/Foo/Test.php',
+            'src/Bar/Baz.php',
+            'src/Example/Test.php',
+        ], [
+            'src/Foo/Test.php',
+            'src/Bar/Baz.php',
+        ]];
+    }
+
+    private function assertFilter(string $filter, iterable $input, array $expected): void
```
[the remark this answers is not in the document]
Comment (sanmai) [reply tests/phpunit/FileSystem/SourceFileFilterTest.php]: OK, done

File: tests/phpunit/FileSystem/SourceFileFilterTest.php (hunk 36 above)
Comment (sanmai) [reply tests/phpunit/FileSystem/SourceFileFilterTest.php]: Yes, here we can see that downstream can take not only arrays, but interables in general.

File: src/Mutation/FileMutationGenerator.php (hunk 37 above)
Comment (sanmai) [reply src/Mutation/FileMutationGenerator.php]: Fixed

File: src/TestFramework/Coverage/CoveredFileNameFilter.php (hunk 34 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileNameFilter.php]: CoveredFileNameFilter is no more.

File: src/Mutation/MutationGenerator.php (hunk 32 above)
Comment (sanmai) [reply src/Mutation/MutationGenerator.php]: Alright, done

File: src/Configuration/Configuration.php [hunk 48]
```diff
@@ -92,6 +93,7 @@ public function __construct(
         int $timeout,
         array $sourceDirectories,
         iterable $sourceFiles,
+        string $filter,
```
[the remark this answers is not in the document]
Comment (sanmai) [reply src/Configuration/Configuration.php]: OK, done

File: tests/phpunit/FileSystem/SourceFileFilterTest.php [hunk 49]
```diff
@@ -0,0 +1,140 @@
...
+
+        yield ['', [
+            'src/Foo/Test.php',
+            'src/Bar/Baz.php',
+            'src/Example/Test.php',
+        ], [
+            'src/Foo/Test.php',
+            'src/Bar/Baz.php',
+            'src/Example/Test.php',
+        ]];
```
[the remark this answers is not in the document]
Comment (sanmai) [reply tests/phpunit/FileSystem/SourceFileFilterTest.php]: This is what you get when you have only 12 inch display. Fixing this now.

File: src/TestFramework/Coverage/CoveredFileData.php (hunk 38 above)
Comment (sanmai) [reply src/TestFramework/Coverage/CoveredFileData.php]: Removed

File: src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php (hunk 43 above)
Comment (sanmai) [reply src/TestFramework/Coverage/XmlReport/FileCodeCoverageProvider.php]: The reason they are so is because I wanted to keep tests as verbatim as possible. I don't recall other reason so they might be merged later just as well.

**Comment by theofidry** [comment]
I feel like this PR will never end if we keep going :) So I would suggest to merge it as is and address the comments later on.

I'm usually not fond of that approach but hey, either we try to improve the underlying bits to enable that PR to be smaller, but that's gonna take a lot of efforts and time, or we go as is which is still a satisfactory state and fix the issues later on

**Comment by sanmai** [comment]
Thank you @maks-rafalko and @theofidry
