### PR TITLE
PhpProcess: Reset $_ENV if it is in use

### LINKED ISSUE #692: "No code coverage driver is available" when running Infection with "variables_order" set to "EGPCS"
| Question    | Answer
| ------------| ---------------
| Infection version | 0.12.2
| Test Framework version | PHPUnit 8.1.2
| PHP version | 7.3.2
| Platform    | Docker (image php:7.3-cli)
| Github Repo | - https://github.com/CViniciusSDias/google-crawler


I'm having trouble running infection inside my Docker container.

When I run it (`vendor/bin/infection`) I get the "Code Coverage does not exist" error even with xdebug enabled.

If I run the exact command it suggests (`'/app/vendor/phpunit/phpunit/phpunit' '--configuration' '/tmp/infection/phpunitConfiguration.initial.infection.xml'`) before and then specify the `--coverage` it works...

I tried adding `phpunit` to $PATH. Installed `infection` globally. Nothing worked.

PS: For a quicker test, remove (or comment) the "all" and "functional" testsuites and run it only with "unit" suite. It fails the same way but quicker.

<details>
 <summary>Output with issue</summary>
 
 ```
You are running Infection with Xdebug enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

Running initial test suite...

PHPUnit version: 8.1.2

   28 [============================] < 1 sec
In CoverageDoesNotExistException.php line 55:
                                                                                                                                                                                         
  Code Coverage does not exist. File /tmp/infection/coverage-xml/index.xml is not found. Check phpunit version Infection was run with and generated config files inside /tmp/infection.  
  Command line: '/app/vendor/phpunit/phpunit/phpunit' '--configuration' '/tmp/infection/phpunitConfiguration.initial.infection.xml'                                                      
  Process Output: PHPUnit 8.1.2 by Sebastian Bergmann and contributors.                                                                                                                  
                                                                                                                                                                                         
  Random seed:   1557693865                                                                                                                                                              
  Error:         No code coverage driver is available                                                                                                                                    
                                                                                                                                                                                         
  .........................                                         25 / 25 (100%)                                                                                                       
                                                                                                                                                                                         
  Time: 29 ms, Memory: 4.00 MB                                                                                                                                                           
                                                                                                                                                                                         
  OK (25 tests, 28 assertions)                                                                                                                                                           
                                                                                                                                                                                         
   Make sure to either:                                                                                                                                                                  
  - Enable xdebug and run infection again                                                                                                                                                
  - Use phpdbg: phpdbg -qrr infection                                                                                                                                                    
  - Use --coverage option with path to the existing coverage report                                                                                                                      
  - Use --initial-tests-php-options option with `-d zend_extension=xdebug.so` and/or any extra php parameters
 ```
</details>

### PR DESCRIPTION
**Pull request by sanmai**
As of 1.3.2 xdebug-handler won't update $_ENV if it is in use. But Symfony's Process will happily import everything from $_ENV, hence we need to reset it just as xdebug-handler does.

- [x] An E2E test probably needed.

Fixes #692

Related: https://github.com/composer/xdebug-handler/pull/95

### CODE REVIEW

**Comment by sanmai** [comment]
Travis builds are failing because of MSI: changes in PhpProcess are covered only by an E2E test.

File: src/Console/Util/PhpProcess.php [hunk 1]
```diff
@@ -63,7 +63,23 @@ public function start(callable $callback = null, array $env = null): void
         $phpConfig = new PhpConfig();
 
         $phpConfig->useOriginal();
+
+        // As of 1.3.2 xdebug-handler won't update $_ENV if it is in use.
```
Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: Is it about these lines of code?

https://github.com/composer/xdebug-handler/blob/0af624bc9c20a3c9252793625bbe976af082d401/src/Process.php#L145-L159

Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: Is it about these lines of code?

https://github.com/composer/xdebug-handler/blob/0af624bc9c20a3c9252793625bbe976af082d401/src/Process.php#L145-L159

File: src/Console/Util/PhpProcess.php [hunk 2]
```diff
@@ -63,7 +63,23 @@ public function start(callable $callback = null, array $env = null): void
...
+        // But Symfony's Process will happily import everything from $_ENV,
```
Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: Is it about these lines of code? 

https://github.com/symfony/process/blob/c43b190e78aa3cd0b17a9d12212b84590b4ead52/Process.php#L1644-L1648

File: src/Console/Util/PhpProcess.php [hunk 3]
```diff
@@ -63,7 +63,23 @@ public function start(callable $callback = null, array $env = null): void
...
+        // hence we need to reset it just as xdebug-handler does
```
Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: Seems like xdebug-handler not just unsets, but set the key to some value:

https://github.com/composer/xdebug-handler/blob/0af624bc9c20a3c9252793625bbe976af082d401/src/Process.php#L153-L157

What is the value of `$unset` variable here when the bug is reproduced? (`true` / `false`)?

File: src/Console/Util/PhpProcess.php (hunk 1 above)
Comment (sanmai) [reply src/Console/Util/PhpProcess.php]: Yes, exactly these. Also see https://github.com/composer/xdebug-handler/pull/95

File: src/Console/Util/PhpProcess.php (hunk 3 above)
Comment (sanmai) [reply src/Console/Util/PhpProcess.php]: We also set it later to the correct value.

File: src/Console/Util/PhpProcess.php (hunk 2 above)
Comment (sanmai) [reply src/Console/Util/PhpProcess.php]: Exactly.
