### PR TITLE
Fix calculation of node range

### LINKED ISSUE #815: false positives since update to 0.14.x
| Question    | Answer
| ------------| ---------------
| Infection version | 0.14.2
| Test Framework version | phpunit 8.4.2
| PHP version | PHP 7.3.8-1
| Platform    | Ubuntu
| Github Repo | https://github.com/chubbyphp/petstore

Since the update fom 0.13.x to 0.14.x i've got many false positives in https://github.com/chubbyphp/petstore but also in projects at work. The all have in common, that they are about multidimensional arrays (pure unit tests). If i change the infection manually tests get red.

<details>

```diff
1) /var/www/html/app/Config/ProdConfig.php:22    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


2) /var/www/html/app/Config/ProdConfig.php:23    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


3) /var/www/html/app/Config/ProdConfig.php:27    [M] FalseValue

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => true, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


4) /var/www/html/app/Config/ProdConfig.php:29    [M] DecrementInteger

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7199], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


5) /var/www/html/app/Config/ProdConfig.php:29    [M] IncrementInteger

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7201], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


6) /var/www/html/app/Config/ProdConfig.php:31    [M] FalseValue

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => true, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


7) /var/www/html/app/Config/ProdConfig.php:32    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


8) /var/www/html/app/Config/ProdConfig.php:33    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => [], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


9) /var/www/html/app/Config/ProdConfig.php:34    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => []], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


10) /var/www/html/app/Config/ProdConfig.php:36    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


11) /var/www/html/app/Config/ProdConfig.php:41    [M] IncrementInteger

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5433, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


12) /var/www/html/app/Config/ProdConfig.php:41    [M] DecrementInteger

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5431, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


13) /var/www/html/app/Config/ProdConfig.php:47    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => [], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


14) /var/www/html/app/Config/ProdConfig.php:48    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => [], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {


15) /var/www/html/app/Config/ProdConfig.php:49    [M] ArrayItemRemoval

--- Original
+++ New
@@ @@
     {
         $cacheDir = $this->getCacheDir();
         $logDir = $this->getLogDir();
-        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => ['type' => 'apcu'], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
+        return ['cors' => ['allow-origin' => [], 'allow-methods' => ['DELETE', 'GET', 'POST', 'PUT'], 'allow-headers' => ['Accept', 'Content-Type'], 'allow-credentials' => false, 'expose-headers' => [], 'max-age' => 7200], 'debug' => false, 'doctrine.dbal.db.options' => ['configuration' => ['cache.result' => ['type' => 'apcu']], 'connection' => ['charset' => 'utf8', 'dbname' => 'petstore', 'driver' => 'pdo_pgsql', 'host' => 'postgres', 'port' => 5432, 'password' => 'root', 'user' => 'root']], 'doctrine.orm.em.options' => ['cache.hydration' => ['type' => 'apcu'], 'cache.metadata' => ['type' => 'apcu'], 'cache.query' => [], 'proxies.dir' => $cacheDir . '/doctrine/proxies'], 'monolog' => ['name' => 'petstore', 'path' => $logDir . '/application.log', 'level' => Logger::NOTICE], 'routerCacheFile' => $cacheDir . '/routes.php'];
     }
     protected function getEnv() : string
     {
```

</details>

Same applies to mocked methods with multidimensional arrays.

<details>

```diff
16) /var/www/html/app/Mapping/Orm/PetMapping.php:27    [M] TrueValue

--- Original
+++ New
@@ @@
         $metadata->setPrimaryTable(['name' => 'pet']);
         $metadata->mapField(['id' => true, 'fieldName' => 'id', 'type' => 'guid']);
         $metadata->mapField(['fieldName' => 'createdAt', 'type' => 'datetime']);
-        $metadata->mapField(['fieldName' => 'updatedAt', 'type' => 'datetime', 'nullable' => true]);
+        $metadata->mapField(['fieldName' => 'updatedAt', 'type' => 'datetime', 'nullable' => false]);
         $metadata->mapField(['fieldName' => 'name', 'type' => 'string']);
         $metadata->mapField(['fieldName' => 'tag', 'type' => 'string', 'nullable' => true]);
     }
 }

17) /var/www/html/app/Mapping/Orm/PetMapping.php:36    [M] TrueValue

--- Original
+++ New
@@ @@
         $metadata->mapField(['fieldName' => 'createdAt', 'type' => 'datetime']);
         $metadata->mapField(['fieldName' => 'updatedAt', 'type' => 'datetime', 'nullable' => true]);
         $metadata->mapField(['fieldName' => 'name', 'type' => 'string']);
-        $metadata->mapField(['fieldName' => 'tag', 'type' => 'string', 'nullable' => true]);
+        $metadata->mapField(['fieldName' => 'tag', 'type' => 'string', 'nullable' => false]);
     }
 }
```

</details>

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR:

* Fixes #815 
* Checks node range outside of the function signature
* Introduces a new class to calculate line ranges

The line range for arrays was originally only calculated while on the function signature. This was
a bug, and that if shouldn't have been there.

### CODE REVIEW

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+
+use Infection\Container;
+use Infection\TestFramework\Coverage\LineRangeCalculator;
+use Infection\Visitor\ParentConnectorVisitor;
+use PhpParser\Node;
+use PhpParser\NodeTraverser;
+use PhpParser\NodeVisitorAbstract;
+use PHPUnit\Framework\TestCase;
+
+final class LineRangeCalculatorTest extends TestCase
```
Comment (theofidry) [inline tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: I know you like to keep state within the test method, but I think you are taking it too much to the extreme here. Fro your two test cases the only non-identical pieces of codes are:

- the `$code` content
- the range value found

The rest (so 8LoC/10 in each test method - counting `$code` as one) are _identical_.

Besides being an indicator that this could be moved in a `setUp()` method, I think this case is a prime example where a data provider would be more appropriate:

```php
/**
 * @dataProvider rangeProvider
 * 
 * @param int[] $expectedRange
 */
public function test_it_can_find_the_appropriate_range(string $code, array $expectedRange)
{
  // ...
}

public function rangeProvider(): Generator
{
    // See https://github.com/infection/infection/issues/815
    yield 'outer most array' => [];

    yield 'range outside of array' => [];
}
```

This also opens the door for easily adding more scenarios without the faff of writing a new test method

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+{
+    /**
+     * @see https://github.com/infection/infection/issues/815
+     */
+    public function test_it_can_find_the_outer_most_array(): void
+    {
+        $parser = Container::create()->getParser();
```
Comment (theofidry) [inline tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: The container and parser is being instantiated each time here which is not ideal... Not that the cost is great for now at least. Maybe I should check for having a `StaticContainer` for the tests

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+        $code = <<<'PHP'
```
Comment (theofidry) [inline tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: I like using "production" code but this one is quite verbose... Would it be possible to have a less verbose one capturing the issue?

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php [hunk 4]
```diff
@@ -0,0 +1,175 @@
...
+        $traverser = new NodeTraverser();
+        $spy = $this->spyTraverser();
+        $traverser->addVisitor(new ParentConnectorVisitor());
+        $traverser->addVisitor($spy);
+        $traverser->traverse($nodes);
+        $range = $spy->range;
+        $this->assertSame([6], $range);
+    }
+
+    private function spyTraverser()
```
Comment (theofidry) [inline tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: `createSpyTraverser()`? It's a bit confusing as otherwise you expect an _action call_ (with no return)

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php [hunk 5]
```diff
@@ -0,0 +1,175 @@
...
+PHP;
+
+        $nodes = $parser->parse($code);
+        $traverser = new NodeTraverser();
+        $spy = $this->spyTraverser();
+        $traverser->addVisitor(new ParentConnectorVisitor());
+        $traverser->addVisitor($spy);
+        $traverser->traverse($nodes);
+        $range = $spy->range;
+        $this->assertSame([6], $range);
```
Comment (theofidry) [inline tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: Might be just me but I find that adding some spaces here would add quite a bit of readability:

```php
        $traverser = new NodeTraverser();
        $traverser->addVisitor(new ParentConnectorVisitor());
        $traverser->addVisitor($spy = $this->spyTraverser());

        $traverser->traverse($parser->parse($code));

        $range = $spy->range;

        $this->assertSame([6], $range);
```

File: src/TestFramework/Coverage/LineRangeCalculator.php [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+
+use Infection\Visitor\ParentConnectorVisitor;
+use PhpParser\Node;
+
+/**
+ * @internal
+ */
+final class LineRangeCalculator
+{
+    public function getNodeRange(Node $node): NodeLineRangeData
```
Comment (theofidry) [inline src/TestFramework/Coverage/LineRangeCalculator.php]: `calculateRange()`?

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php (hunk 2 above)
Comment (BackEndTea) [reply tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: I've 'cached' the prarser in a static class variable

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php (hunk 3 above)
Comment (BackEndTea) [reply tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: I've reduced the footprint of the production code to just the array wrapped inside of a function.

Its still a bit verbose, but less so now.

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php (hunk 4 above)
Comment (BackEndTea) [reply tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: Probably a better name, updated it.

The reason there is no return type is that this makes it harder for tooling to understand the class that is returned by this method has a `range` property

File: tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php (hunk 3 above)
Comment (BackEndTea) [reply tests/phpunit/TestFramework/Coverage/LineRangeCalculatorTest.php]: I've reduced the footprint of the production code to just the array wrapped inside of a function.

Its still a bit verbose, but less so now.
