### PR TITLE
Removed php include args handling.

### LINKED ISSUE #600: Space in PHP interpreter path breaks Infection
| Question    | Answer
| ------------| ---------------
| Infection version |  0.11.4
| Test Framework version | PHPUnit 7.5.1
| PHP version | 7.2.2
| Platform | Windows
| Github Repo | https://github.com/keboola/php-temp/tree/ec31be07422ba7dd5f9a5a032929686aaa65abce

Running infection fails when PHP interpreter is located in path containing spaces.

\> php infection.phar

gives:
```
In Process.php line 135:

  The command "C:\Program Files\Php\php.exe D:\php-temp\vendor\phpunit\phpunit\phpunit --version" failed.

  Exit Code: 1(General error)

  Working directory: D:\php-temp

  Output:
  ================


  Error Output:
  ================
  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
```

I've traced this down to: https://github.com/infection/infection/blob/7894cf5f6030c3c499004d57f7a29db52aeb2af8/src/TestFramework/AbstractTestFrameworkAdapter.php#L242

where replacing `explode(' ', $phpPath);` with `$this->cachedPhpPath = [$phpPath]`; fixes the problem (but is probably not a solution).

### PR DESCRIPTION
**Pull request by siad007**
This PR:

- [x] Fixes space in path issue under windows
- [x] Covered by tests
- [x] Doc PR: We should remove the php argument handling and add the argument for phpdbg separat.

Fixes #600

### CODE REVIEW

File: src/TestFramework/AbstractTestFrameworkAdapter.php [hunk 1]
```diff
@@ -229,17 +227,20 @@ public function getInitialTestsFailRecommendations(string $commandLine): string
      *
      * @return string[]
      */
-    private function findPhp(bool $includeArgs = true): array
+    private function findPhp(): array
     {
-        if ($this->cachedPhpPath === null || $this->cachedIncludedArgs !== $includeArgs) {
-            $this->cachedIncludedArgs = $includeArgs;
-            $phpPath = (new PhpExecutableFinder())->find($includeArgs);
+        if ($this->cachedPhpPath === null) {
```
Comment (sidz) [inline src/TestFramework/AbstractTestFrameworkAdapter.php]: it's not a php path tbh. Probably we should rename this property.

also we should drop `$cachedIncludedArgs` as it's no longer required

File: src/TestFramework/AbstractTestFrameworkAdapter.php [hunk 2]
```diff
@@ -229,20 +217,21 @@ public function getInitialTestsFailRecommendations(string $commandLine): string
      *
      * @return string[]
      */
-    private function findPhp(bool $includeArgs = true): array
+    private function findPhp(): array
     {
-        if ($this->cachedPhpPath === null || $this->cachedIncludedArgs !== $includeArgs) {
-            $this->cachedIncludedArgs = $includeArgs;
-            $phpPath = (new PhpExecutableFinder())->find($includeArgs);
+        $phpExec = (new PhpExecutableFinder())->find(false);
```
Comment (sidz) [inline src/TestFramework/AbstractTestFrameworkAdapter.php]: `$this->cachedPhpPath` property was required. I've just thought about renaming.

We don't want to execute `find` more then once. Fine with me if it'll just check on non empty.
