### PR TITLE
Use a transparent xdebug-free environment for all but the initial test process

### LINKED ISSUE #306: Initial test suite may fail to deliver coverage, e.g. under Docker
If there's env var `PHP_INI_SCAN_DIR=""`, then PHP won't load xdebug from additional .ini files.

PHP_INI_SCAN_DIR is set to an empty string in ConfigBuilder since in 47c8350d1:
https://github.com/infection/infection/blob/79c873663e088a3cbaf3a7a1cd7600f25845fb90/src/Php/ConfigBuilder.php#L88

### Steps to reproduce

```bash
docker build -t infection_php70 -f "$PWD/devTools/Dockerfile-php70-xdebug" .
docker run -it --rm -v "$PWD":/opt/infection -w /opt/infection infection_php70 bin/infection
```

### Expected result 

No errors found during initial testing.

### Actual result

```
Project tests must be in a passing state before running Infection.  
                                                                    
Phpunit reported an exit code of 2.                                 
                                                                    
Refer to the phpunit's output below:                                

There was 1 error:                                                                                            
                                                                                                              
1) Infection\Tests\Php\XdebugHandlerTest::test_it_restart_when_loaded                                         
Symfony\Component\Filesystem\Exception\IOException: Can not create temporary php config with disabled xdebug. 
                                                                                                              
/opt/infection/src/Php/ConfigBuilder.php:57                                                                   
/opt/infection/src/Php/XdebugHandler.php:83                                                                   
/opt/infection/src/Php/XdebugHandler.php:53                                                                   
/opt/infection/tests/Php/XdebugHandlerTest.php:67                                                             


```

### Discussion

With an additional test added somewhere at the beginning of the suite Infection would tell right away what's the problem.

```patch
diff --git a/tests/Config/Exception/InvalidConfigExceptionTest.php b/tests/Config/Exception/InvalidConfigExceptionTest.php
index 3b96bba..b589beb 100644
--- a/tests/Config/Exception/InvalidConfigExceptionTest.php
+++ b/tests/Config/Exception/InvalidConfigExceptionTest.php
@@ -14,6 +14,11 @@ use PHPUnit\Framework\TestCase;
 
 final class InvalidConfigExceptionTest extends TestCase
 {
+    public function test_quick_xdebug_check()
+    {
+        $this->assertTrue(extension_loaded('xdebug') || 'phpdbg' == PHP_SAPI);
+    }
+
     public function test_extends_runtime_exception()
     {
         $exception = new InvalidConfigException();
```
Outputs:
```
Phpunit reported an exit code of 1.                                                       
                                                                                          
Refer to the phpunit's output below:                                                      
                                                                                          
STDOUT:                                                                                   
                                                                                          
PHPUnit 6.1.0 by Sebastian Bergmann and contributors.                                     
                                                                                          
Error:         No code coverage driver is available                                       
                                                                                          
F                                                                                         
                                                                                          
Time: 773 ms, Memory: 12.00MB                                                             
                                                                                          
There was 1 failure:                                                                      
                                                                                          
1) Infection\Tests\Config\Exception\InvalidConfigExceptionTest::test_quick_xdebug_check   
Failed asserting that false is true.                                                      
                                                                                          
/opt/infection/tests/Config/Exception/InvalidConfigExceptionTest.php:19                   
                                                                                          
FAILURES!                                                                                 
Tests: 1, Assertions: 1, Failures: 1.                                                     
```

So this boils down to `PHP_INI_SCAN_DIR` somehow polluting environment when running on Docker. No such problem exists outside of running under Docker.

### Guilty as charged

This issue exists because of [a peculiarity of how XdebugHandler handles environment](https://github.com/composer/xdebug-handler):

> In addition to the ini files issue outlined above, PHP_INI_SCAN_DIR is not restored in the sub-process (unless xdebug-hander is implemented). This will cause problems if it was changed and the sub-process calls another PHP process.

Otherwise put, XdebugHandler does exactly what we observer here.

### LINKED ISSUE #332: Weird behaviour in Docker container
| Question    | Answer
| ------------| ---------------
| Infection version | 0.8.1
| Test Framework version | PHPUnit 7.1.5
| PHP version | 7.1.16
| Platform    | Docker `php:7.1`
| Github Repo | https://github.com/trinet-at/docker-infection

I use GitLab and the gitlab-ci task runner for testing my projects. The runner uses Docker to execute the tasks, having `php:7.1` as base image. When I added infection to my project I noticed a weird behavior when infection runs in the container. Locally everything works fine.
Infection complains that a required extension, in this test case the `intl` extension is not loaded, although it is.

To replicate the problem I created a small test scenario which uses the `Locale` class from `intl` from which the problem can be reproduced.

```
git clone https://github.com/trinet-at/docker-infection.git
cd docker-infection
composer install
docker build -t docker-infection .
```

Locally, infection runs fine:
`vendor/bin/infection`

If I run infection in the Docker container the error occurs (`vendor/bin/infection` is the default `CMD` in the image)

`docker run --rm -it -v $PWD:/app docker-infection`

However, running PHPUnit completes without a problem:
`docker run --rm -it -v $PWD:/app docker-infection vendor/bin/phpunit`

Also, running the `infection.phar` (installed as executable in `/usr/local/bin` in the image) succeeds:
`docker run --rm -it -v $PWD:/app docker-infection infection.phar`

The "solution" is to combine all of the `.ini` files of PHP into one `php.ini`.
There's a script in the repo which does exactly that and runs `vendor/bin/infection` afterwards:
`docker run --rm -it -v $PWD:/app docker-infection ./convert-ini.sh`

So it seems to me that infection somehow runs PHPunit in a non-standard way.

Does anybody have a solution for that without having to use the `.phar` file or combining PHP's `.ini` files? Maybe it's somehow related to issue #306.

Thanks!

### PR DESCRIPTION
**Pull request by sanmai**
Fixes #306
Fixes #332

(`make test` still fails because of missing `expect`, #304 should fix this problem too)

### CODE REVIEW

File: src/Console/Util/PhpProcess.php [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+        self::setupEnvironment();
+    }
+
+    private static function restoreVanillaEnvironment()
+    {
+        self::putenv('PHPRC', self::$phprc);
+        self::putenv('PHP_INI_SCAN_DIR', XdebugHandler::getRestartSettings()['scanDir']);
+    }
+
+    private static function putenv($name, $value)
```
Comment (BackEndTea) [inline src/Console/Util/PhpProcess.php]: `$value` can be a string or a bool, but `$name` should always be a string.
Could we change this to `private static function putenv(string $name, $value)`, and add a doc block to help IDE's understand that value can be either

File: src/Console/Util/PhpProcess.php [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+use Symfony\Component\Process\Process;
+
+/**
+ * Vanilla PHP process and utility functions
+ *
+ * @internal
+ */
+final class PhpProcess extends Process
+{
+    private static $phprc;
```
Comment (BackEndTea) [inline src/Console/Util/PhpProcess.php]: Can we add the following doc block here?
```php
/**
 * @var string|bool
 */
```

File: src/Process/Builder/ProcessBuilder.php [hunk 3]
```diff
@@ -49,24 +50,25 @@ public function getProcessForInitialTestRun(
...
                 $this->testFrameworkAdapter->buildInitialConfigFile(),
                 $testFrameworkExtraOptions,
                 $includeArgs,
                 $phpExtraOptions
             ),
             null,
-            $includeArgs ? array_replace($_ENV, $_SERVER) : null,
+            null,
             null,
             null
```
Comment (BackEndTea) [inline src/Process/Builder/ProcessBuilder.php]: Instead off `null, null, ...` what about skiping those and doing a `$process->setTimeout(null)` afterwards?

I'm not sure which one is cleaner, what do you think?

Comment (sanmai) [reply src/Process/Builder/ProcessBuilder.php]: Yes, that's definitely better than `null, null, null, null`

**Comment by BackEndTea** [comment]
This looks ready to merge for me.

File: src/Console/Util/PhpProcess.php [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+
+    /**
+     * Setups a default Xdebug-free environment for all subprocesses:
+     *
+     * - PHPRC should point to our temporary php.ini (we need to save a previous value)
+     *
+     * - PHP_INI_SCAN_DIR should be made blank because our php.ini has all we need
+     *   (a previous value can be found in XdebugHandler::getRestartSettings()["scanDir"])
+     */
+    public static function setupEnvironment()
```
Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: I suggest to rename it to smth like `setupXdebugFreeSubprocessesEnvironment()` or `setupXdebugFreeEnvironmentForSubprocesses()` or at least `setupXdebugFreeEnvironment()`.

It confused me each time I saw this method call because of the too general name.

What do you think?

File: src/Console/Util/PhpProcess.php [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+    public function start(callable $callback = null, array $env = null)
+    {
+        // Xdebug wasn't skipped, running as is
+        if ('' == XdebugHandler::getSkippedVersion()) {
+            parent::start($callback, $env);
+
+            return;
+        }
+
+        self::restoreVanillaEnvironment();
```
Comment (borNfreee) [inline src/Console/Util/PhpProcess.php]: 1. Am I right that we need to restore original env here because it was set up by calling `->setupEnvironment()` on `Application.php`?

2. what do you think about `restoreOriginalEnvironment()`? feel free to ignore

3. would you mind adding some comments here about why we restore and then setup xdebug-free env again? I would highly simplify understanding of the whole feature

Comment (sanmai) [reply src/Console/Util/PhpProcess.php]: 1. That's correct, only we have no choice of *not* calling `setupEnvironment()` in `Application.php`.

2. "Vanilla" is very concrete, "original" is not as much. Where vanilla means the very-very original environment, just an original environment could be some other environment.

3. I'll see to it.

File: src/Console/Util/PhpProcess.php (hunk 4 above)
Comment (sanmai) [reply src/Console/Util/PhpProcess.php]: That's good to go.

**Comment by sanmai** [comment]
@borNfreee I've got this rebased over master, Travis repors all green after some fixing

**Comment by borNfreee** [comment]
Thank you @sanmai
