### PR TITLE
Validate phpunit.xml

### LINKED ISSUE #409: Infection does not fail gracefully on an invalid phpunit.xml
For example, for this `phpunit.xml`:
```xml
<invalid>
</invalid>
```
Infection fails with:

```
PHP Fatal error:  Uncaught Error: Call to a member function setAttribute() on null in 
src/TestFramework/PhpUnit/Config/XmlConfigurationHelper.php:62
```

### PR DESCRIPTION
**Pull request by borNfreee**
This PR:

- [x] Fixes #409
- [x] Add `phpunit.xml` validation: by checking the root node and then by XSD schema if needed/possible. XSD can be validated with local and remote (http[s]) paths to files
- [x] Adds `ext-libxml` to the list of required extensions. This is *not a new requirement*, just made it explicit by adding to `composer.json`

### CODE REVIEW

**Comment by localheinz** [comment]
Also see https://github.com/sebastianbergmann/phpunit/commit/d4484be1a9c56c73353517510ce3b0690f6d738e.

File: src/TestFramework/PhpUnit/Config/Exception/InvalidPhpUnitXmlConfigException.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+namespace Infection\TestFramework\PhpUnit\Config\Exception;
+
+/**
+ * @internal
+ */
+final class InvalidPhpUnitXmlConfigException extends \RuntimeException
+{
+    public static function byRootNode(): self
+    {
+        return new self('phpunit.xml does not contain a valid PHPUit configuration.');
```
Comment (localheinz) [inline src/TestFramework/PhpUnit/Config/Exception/InvalidPhpUnitXmlConfigException.php]: Note that there is an `n`missing here.

File: tests/TestFramework/PhpUnit/Config/XmlConfigurationHelperTest.php [hunk 2]
```diff
@@ -232,6 +233,77 @@ public function test_it_removes_existing_printers(): void
         );
     }
 
+    public function test_it_validates_xml_by_root_node(): void
+    {
+        $this->expectException(InvalidPhpUnitXmlConfigException::class);
+        $this->expectExceptionMessage('phpunit.xml does not contain a valid PHPUnit configuration.');
```
Comment (localheinz) [inline tests/TestFramework/PhpUnit/Config/XmlConfigurationHelperTest.php]: How about moving this block to right before performing the action instead?

For reference, also see https://thephp.cc/news/2016/02/questioning-phpunit-best-practices.

Comment (borNfreee) [reply tests/TestFramework/PhpUnit/Config/XmlConfigurationHelperTest.php]: Done

**Comment by borNfreee** [comment]
Thank you @localheinz and @sidz
