### PR TITLE
Fix PHPStan running out of memory during initial static analysis

### LINKED ISSUE #2417: PHPStan running out of memory when attempting --static-analysis-tool=phpstan
| Question    | Answer
| ------------| ---------------
| Infection version | 0.31.2
| Test Framework version | PHPUnit 12.3.6
| PHP version | 8.4.11
| Platform    | Ubuntu/Alpine Container
| Github Repo | https://github.com/WyriHaximus/Makefiles/pull/46

<details>
 <summary>infection.json5</summary>

 ```json5
{
    "timeout": 120,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "../../var/infection.log",
        "summary": "../../var/infection-summary.log",
        "json": "../../var/infection.json",
        "perMutator": "../../var/infection-per-mutator.md",
        "github": true
    },
    "minMsi": 100,
    "minCoveredMsi": 100,
    "ignoreMsiWithNoMutations": true,
    "mutators": {
        "@default": true
    }
}
 ```
</details>

<details>
 <summary>phpunit.xml</summary>

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bootstrap="../../vendor/autoload.php" colors="true" xsi:noNamespaceSchemaLocation="../../vendor/phpunit/phpunit/phpunit.xsd" cacheDirectory="../../var/phpunit/cache">
    <testsuites>
        <testsuite name="Test Suite">
            <directory>../../tests/</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory suffix=".php">../../src/</directory>
        </include>
    </source>
    <extensions>
        <bootstrap class="Ergebnis\PHPUnit\SlowTestDetector\Extension"/>
    </extensions>
</phpunit>
 ```
</details>

<details>
 <summary>Output with issue</summary>

Image

</details>

Memory limit in the container is set to `-1` via `php -i | grep memory`:

```
memory_limit => -1 => -1
Collecting memory statistics => No
Shared memory model => mmap
Used memory => 34333768
Free memory => 1039408056
Wasted memory => 0
Interned Strings Used memory => 8860120
Interned Strings Free memory => 24694312
opcache.memory_consumption => 1024 => 1024
opcache.preferred_memory_model => no value => no value
opcache.protect_memory => Off => Off
```

### PR DESCRIPTION
**Pull request by sanmai**
## Summary
Fixes #2417 - PHPStan running out of memory when using `--static-analysis-tool=phpstan`

## Problem
The MemoryLimiter was applying memory restrictions calculated from the test suite run **before** the initial PHPStan analysis executed. This caused PHPStan to inherit overly restrictive memory limits (e.g., 24MB) and crash with "Allowed memory size exhausted" errors.

## Root Cause
In `Engine::execute()`, the flow was:
1. Run initial test suite → calculate memory usage
2. **Apply memory limit to php.ini** ← Problem happens here
3. Run PHPStan (inherits the restrictive limit)
4. Run mutation testing

## Solution
Move the `limitMemory()` call to execute **after** both initial runs complete:
1. Run initial test suite → store output
2. Run PHPStan (unrestricted memory)
3. **Apply memory limit** ← Moved here
4. Run mutation testing (gets the limit as intended)

## Changes
- Modified `Engine::runInitialTestSuite()` to return test output instead of applying limits immediately
- Moved `limitMemory()` call in `Engine::execute()` to after `runInitialStaticAnalysis()`
- Added null check for scenarios where initial tests are skipped

## Testing
- ✅ Unit tests pass (EngineTest, MemoryLimiterTest)
- ✅ Verified [with bug reproducer](https://github.com/infection/infection/issues/2417#issuecomment-3374458076) - PHPStan v2.1.29 completes successfully
- ✅ Mutation testing still receives memory limits as intended

## Impact
- No breaking changes
- No configuration changes needed for users
- Memory limiter still functions correctly for mutation testing processes

### CODE REVIEW

**Review by sanmai — COMMENTED** [review]
Yeah, it actually makes sense.

File: src/Engine.php [hunk 1]
```diff
@@ -89,8 +89,18 @@ public function __construct(
      */
     public function execute(): void
     {
-        $this->runInitialTestSuite();
+        $initialTestSuiteOutput = $this->runInitialTestSuite();
         $this->runInitialStaticAnalysis();
```
Comment (sanmai) [inline src/Engine.php:93]: A far shorter fix would be to swap these two lines into:

```
$this->runInitialStaticAnalysis();
$this->runInitialTestSuite();
```

Comment (maks-rafalko) [reply src/Engine.php:93]: yep, I also considered this one :) 

if I understand this correctly, we can **potentially** still have this problem with memory limiter for "killer" processes later during Mutation Analysis phase, but this is another story. Now we are fixing "initial run" phase. In "killer" processes - we will already have a PHPStan cache, so it should require far less memory.

So what do you think is a more proper solution right now? I'm ok with both (the current PR and swapping), while swapping looks easier / cleaner / less code to update.

Comment (sanmai) [reply src/Engine.php:93]: I'm somewhat torn between these two; one the one hand, running tests first have its merits; on the other hand, does it really that important?

I guess I like the current approach more because it is explicit and will prevent the issue from re-appearing in the future if someone, for example, swaps these two runs backwards. I mean, we can certainly test the order is expected, but is is not as explicit as it is now.

**Review by maks-rafalko — APPROVED** [review]
