### PR TITLE
Round MSI down to the smallest integer, instead of nearest

### LINKED ISSUE #426: 100% MSI reported even if a small number of uncovered mutations is found
Infection may report 100% MSI and won't fail on `--min-msi` if there was a sufficiently large number of mutations. [A quote from our Slack channel:](https://symfony-devs.slack.com/archives/C78M7A4BY/p1533189199000112)

> I guess it’s something like 99.99%  and this value is rounded to 100 https://github.com/infection/infection/blob/master/src/Mutant/MetricsCalculator.php#L137, so it passes --min-msi

### PR DESCRIPTION
**Pull request by sanmai**
Round metrics down to the smallest integer, instead of nearest, which is the worst case for a metric.

Fixes #426

### CODE REVIEW

File: src/Mutant/MetricsCalculator.php [hunk 1]
```diff
@@ -134,7 +134,7 @@ public function getMutationScoreIndicator(): float
         $defeatedTotal = $this->killedCount + $this->timedOutCount + $this->errorCount;
 
         if ($this->totalMutantsCount) {
-            $detectionRateAll = round(100 * ($defeatedTotal / $this->totalMutantsCount));
+            $detectionRateAll = floor(100 * ($defeatedTotal / $this->totalMutantsCount));
```
Comment (borNfreee) [inline src/Mutant/MetricsCalculator.php]: I believe at least Covered MSI (line 167) should also be updated since we used it in `--min-coverered-msi` - the same bug will be here.

And what about `getCoverageRate()`? Probably having the same logic there would be consistent?

Comment (sanmai) [reply src/Mutant/MetricsCalculator.php]: Yes, I think that's going to be more proper to account for the worst case for all metrics.

File: tests/Mutant/MetricsCalculatorTest.php [hunk 2]
```diff
@@ -41,42 +41,40 @@ public function test_it_shows_zero_values_by_default(): void
         $this->assertSame(0.0, $calculator->getCoveredCodeMutationScoreIndicator());
     }
 
+    private function addMutantProcess(MetricsCalculator $calculator, int $resultCode, int $count = 1): void
```
Comment (BackEndTea) [inline tests/Mutant/MetricsCalculatorTest.php]: Should we move this below the test method?

Comment (sanmai) [reply tests/Mutant/MetricsCalculatorTest.php]: It is in reading order and in close proximity. I don't think it would be any better if it would be below.

**Comment by borNfreee** [comment]
Thank you @sanmai
