### PR TITLE
Use new config data when Infection has been executed at the first time

### LINKED ISSUE #576: Infection gets stuck in the first execution after configuration file is created
| Question    | Answer
| ------------| ---------------
| Infection version | 0.11.2 and also master branch
| Test Framework version | PHPUnit 7.4.4
| PHP version | 7.2.12
| Platform    | CentOS 7.5
| Github Repo | -

At the first execution of Infection, it creates infection.json.dist and then it runs testcases. In this time, the configuration is not loaded properly and the execution goes wrong.

<details>
<summary>Output with issue</summary>

In the following output, Infection is executed with phpdbg and breakpoint is set on https://github.com/infection/infection/blob/ab723af4078d0c7cee48c143eb1d037d6fb3ee4e/src/Command/InfectionCommand.php#L207. Here configuration should be loaded properly IMO.

At the first execution (I don't have infection.json.dist)
```
$ phpdbg vendor/bin/infection
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Successful compilation of /tmp/sandbox/vendor/infection/infection/bin/infection]
prompt> break vendor/infection/infection/src/Command/InfectionCommand.php:207
[Breakpoint #0 added at /tmp/sandbox/vendor/infection/infection/src/Command/InfectionCommand.php:207]
prompt> run
You are running Infection with phpdbg enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/



  Welcome to the Infection config generator



We did not find a configuration file. The following questions will help us to generate it for you.


Which source directories do you want to include (comma separated)? [src]:
  [0] .
  [1] src
  [2] src.bak
  [3] tests
  [4] tests.bak
  [5] vendor
 >

There can be situations when you want to exclude some folders from generating mutants.
You can use glob pattern (*Bundle/**/*/Tests) for them or just regular dir path.
It should be relative to the source directory.
You should not mutate test suite files.
Press <return> to stop/skip adding dirs.

Any directories to exclude from within your source directories?:

Single test suite timeout in seconds [10]:

Where do you want to store the text log file? [infection.log]:

Configuration file "infection.json.dist" was created.

[Breakpoint #0 at /tmp/sandbox/vendor/infection/infection/src/Command/InfectionCommand.php:207, hits: 1]
>00207:         $this->includeUserBootstrap($config);
 00208:
 00209:         $testFrameworkKey = $input->getOption('test-framework') ?: $config->getTestFramework();
prompt> ev $config
Infection\Config\InfectionConfig Object
(
    [config:Infection\Config\InfectionConfig:private] => stdClass Object
        (
        )

    [filesystem:Infection\Config\InfectionConfig:private] => Symfony\Component\Filesystem\Filesystem Object
        (
        )

    [configLocation:Infection\Config\InfectionConfig:private] => /tmp/sandbox
)
```
You can see InfectionConfig is empty here, and after this the execution gets stuck.

Second run (infection.json.dist is already created)
```
$ phpdbg vendor/bin/infection
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Successful compilation of /tmp/sandbox/vendor/infection/infection/bin/infection]
prompt> break vendor/infection/infection/src/Command/InfectionCommand.php:207
[Breakpoint #0 added at /tmp/sandbox/vendor/infection/infection/src/Command/InfectionCommand.php:207]
prompt> run
You are running Infection with phpdbg enabled.
     ____      ____          __  _
    /  _/___  / __/__  _____/ /_(_)___  ____
    / // __ \/ /_/ _ \/ ___/ __/ / __ \/ __ \
  _/ // / / / __/  __/ /__/ /_/ / /_/ / / / /
 /___/_/ /_/_/  \___/\___/\__/_/\____/_/ /_/

[Breakpoint #0 at /tmp/sandbox/vendor/infection/infection/src/Command/InfectionCommand.php:207, hits: 1]
>00207:         $this->includeUserBootstrap($config);
 00208:
 00209:         $testFrameworkKey = $input->getOption('test-framework') ?: $config->getTestFramework();
prompt> ev $config
Infection\Config\InfectionConfig Object
(
    [config:Infection\Config\InfectionConfig:private] => stdClass Object
        (
            [timeout] => 10
            [source] => stdClass Object
                (
                    [directories] => Array
                        (
                            [0] => src
                        )

                )

            [logs] => stdClass Object
                (
                    [text] => infection.log
                )

            [mutators] => stdClass Object
                (
                    [@default] => 1
                )

        )

    [filesystem:Infection\Config\InfectionConfig:private] => Symfony\Component\Filesystem\Filesystem Object
        (
        )

    [configLocation:Infection\Config\InfectionConfig:private] => /tmp/sandbox
)
```
In this time, configuration is loaded properly and the execution is successfully finished.
</details>

### PR DESCRIPTION
**Pull request by sanmai**
For one, `InfectionConfig` should be using known default values, but not access the configuration file that is non-existing at the time of configuration. For another, `JsonFile` should not continue as usual even if it is given a non-existing file.

Fixes #576

Kudos to @sidz for his effort in #577 (E2E test there is not exactly correct).

### CODE REVIEW

File: src/Console/InfectionContainer.php [hunk 1]
```diff
@@ -232,12 +232,19 @@ public function __construct(array $values = [])
...
             $facade = new ConfigCreatorFacade($this['locator'], $this['filesystem']);
 
             return $facade->createConfig($input->getOption('configuration'));
         };
 
+        /*
+         * Configuration step needs a distinct instance of a configuration as it may be inexistent.
+         * Therefore we can avoid using this stale and invalid configuration later on.
+         */
+        $this['infection.config.initial'] = $infectionConfigMaker;
```
Comment (sidz) [inline src/Console/InfectionContainer.php]: I'm not sure that this is a good idea to have more than one config class.

Comment (sanmai) [reply src/Console/InfectionContainer.php]: What makes you concerned?

Another option is to re-initialize this `infection.config` maker, which is a painful job with lots of moving parts.

**Comment by sanmai** [comment]
Builds are failing because of #631. Otherwise all seems fine.

File: src/Command/InfectionCommand.php [hunk 2]
```diff
@@ -362,7 +362,7 @@ private function runConfigurationCommand(Locator $locator): void
             $locator->locateOneOf(InfectionConfig::POSSIBLE_CONFIG_FILE_NAMES);
         } catch (\Exception $e) {
             $configureCommand = $this->getApplication()->find('configure');
-            $config = $this->getContainer()->get('infection.config');
+            $config = $this->getContainer()->get('infection.config.initial');
```
Comment (borNfreee) [inline src/Command/InfectionCommand.php]: Seems like the only one reason why `$config` variable is used here is to get default test framework name (`$config->getTestFramework()`) when `infection.json` **does not exist**.

And since config does not exist, it always defaults to `phpunit`.

https://github.com/infection/infection/blob/5b02e8e3c77b10732e69e7aad005946d06a431ad/src/Config/InfectionConfig.php#L155

`$this->config->testFramework` is empty when `infection.json` does not exist. Because of

https://github.com/infection/infection/blob/5b02e8e3c77b10732e69e7aad005946d06a431ad/src/Config/ConfigCreatorFacade.php#L80-L85

If we replace `$config->getTestFramework()` with `TestFrameworkTypes::PHPUNIT`, this will be the same PR as https://github.com/infection/infection/pull/577

I think we don't need `$config` instance here at all.

Comment (sanmai) [reply src/Command/InfectionCommand.php]: I've seen this done in #577, but decided to keep the current behavior. For one because if configuration values are coming from one source, then you don't have to walk around all code changing them. Change them in one place and be done. For another we may have an idea to guess the value in the future. Then, again, everything will be as ready for this as it is. 

I think some of these reasons are behind why this was done like that in the first place.

Do you still think we should stick to PHPUnit defaulting with a plain constant?

Comment (borNfreee) [reply src/Command/InfectionCommand.php]: Apologize for the late reply.

What you say is perfectly valid. The only issue with this particular line of code is that it was my mistake (read "bug") that I've added it here. Let me explain:

This is a commit that adds this config here: https://github.com/infection/infection/commit/2859730b9ffa5678e3a90226cae0d1647f0ff8f6

From git commit message:

> * Use default test framework if neither CLI nor config has the value for it

So, all I wanted to do, is to use **default** test framework when it's impossible to get it neither  from CLI option nor from the config. 

Why it was a mistake? Because `$config->getTestFramework()` is intended return value from `infection.json`, not a default TF. It just has a fallback.

What I think would be the right solution:

instead of calling instance level method `->getTestFramework()`, I would introduce a new static method `::getDefaultTestFramework()` and call it here statically.

1. It would resolve the issue with config initialization, because of a statically called method
2. It would make code more expressive because what we want to do here is really get default TF

Comment (sanmai) [reply src/Command/InfectionCommand.php]: OK, I got what you're thinking. This makes sense.

Comment (sanmai) [reply src/Command/InfectionCommand.php]: I went with `TestFrameworkTypes::PHPUNIT` for now.

(We can make an easy switch to `InfectionConfig::getDefaultTestFramework()` when it'll do anything in particular other than just returning `TestFrameworkTypes::PHPUNIT`.)

**Comment by borNfreee** [comment]
Thank you @sanmai and @sidz
